name: 'Install Salesforce CLI'
description: 'Installs the Salesforce CLI (sf) with optional plugins'
inputs:
  version:
    description: 'The version of the Salesforce CLI to install'
    required: false
    default: 'latest'
  plugins:
    description: 'Comma separate list of plugins to install'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Install the cli
      shell: bash
      run: |
        echo "====> Installing @salesforce/cli@${{ inputs.version }}"
        npm install -g @salesforce/cli@${{ inputs.version }}
        if [ $? -eq 0 ]; then
            echo "Installed the Salesforce CLI successfully."
          else
            echo "!! FAILED TO INSTALL THE Salescore CLI"
            exit 1
          fi

    - name: Install plugins
      id: install-plugins
      if: ${{ inputs.plugins  != ''}}
      shell: bash
      run: |
        plugins="${{ inputs.plugins }}"
        for plugin in ${plugins//,/ }; do
          echo "====> Installing $plugin "
          sf plugins install $plugin
          if [ $? -eq 0 ]; then
            echo "Installed ${plugin} successfully."
          else
            echo "!! FAILED TO INSTALL ${plugin}"
            exit 1
          fi
        done

    - name: Echo what was installed
      shell: bash
      run: |
        echo "\nSALESFORCE CLI VERSION:\n$(sf version --json)"
        echo "\nSALESFORCE CLI PLUGINS:\n$(sf plugins)"